config/routes.rb
Rails.application.routes.draw do
  get 'home/submit_form'
  post 'home/create', defaults: { format: 'json' }
  resources :forms do
    resources :form_elements
    member do
      get :preview, to: 'form_elements#preview'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/field.rb
class Field < ApplicationRecord
end

app/models/form.rb
class Form < ApplicationRecord
  has_many :form_elements, dependent: :destroy
end

app/models/form_element.rb
class FormElement < ApplicationRecord
  belongs_to :form

  # since select is reserved keywork in rails, replace select with select_box
  # enum component_type: %w(textfield email datetime phoneNumber radio select checkbox button)
  enum validation: %w(required maxDate minDate maxLength minLength)

  def self.component_types
    %w(textfield email datetime phoneNumber radio select)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  skip_before_action :verify_authenticity_token, if: :json_request?

  def json_request?
    request.format.json?
  end
end

app/controllers/form_elements_controller.rb
class FormElementsController < ApplicationController
  before_action :set_form, except: [:preview]
  before_action :set_form_element, only: [:edit, :update, :destroy]

  def index
    @form_element = FormElement.new
    @form_elements = @form.form_elements
    ap prepare_json
    @preview_element = JSON.generate(prepare_json)
  end

  def preview
    @form = Form.find(params[:id])
    @form_elements = @form.form_elements
    @preview_element = JSON.generate(prepare_json)
  end

  def edit
  end

  def update
    if @form_element.update_attributes(prepare_params)
      flash[:success] = "Form element has been successfully created"
      redirect_to form_form_elements_path(@form)
    else
      render "edit"
    end
  end

  def create
    @form_elements = @form.form_elements.new(prepare_params)
    if @form_elements.save
      flash[:success] = "Form element has been successfully created"
      redirect_to form_form_elements_path(@form)
    else
      render "new"
    end
  end

  def destroy
    if @form_element.destroy
      flash[:success] = "Form element has been successfully deleted"
      redirect_to form_form_elements_path(@form)
    end
  end

  private
  def prepare_params
    new_allow_params = form_elements_params

    if(form_elements_params[:component_type] == 'textfield' || form_elements_params[:component_type] == 'email' || form_elements_params[:component_type] == 'phoneNumber' || form_elements_params[:component_type] == 'datetime')
      new_allow_params.delete(:datasets)
      new_allow_params.delete(:values)
    end

    if(form_elements_params[:component_type] == 'radio')
      new_allow_params.delete(:datasets)
      new_allow_params[:datasets] = new_allow_params[:values]
      new_allow_params.delete(:values)
    end


    if(form_elements_params[:component_type] == 'select')
      new_allow_params.delete(:values)
    end


    # if(form_elements_params.has_key?(:component_type))
      # ap form_elements_params
      # new_allow_params[:component_type] = replace_component_type(new_allow_params[:component_type])
      # new_allow_params.delete(:component_type)
    # end

    if(form_elements_params.has_key?(:field_validation))
      # new_allow_params[:type] = replace_component_type(new_allow_params[:component_type])

      new_allow_params[:field_validation][:required] = !new_allow_params[:field_validation][:required].blank?
      new_allow_params[:field_validation][:minLength] = new_allow_params[:field_validation][:minLength].to_i unless new_allow_params[:field_validation][:minLength].blank?
      new_allow_params[:field_validation][:maxLength] = new_allow_params[:field_validation][:maxLength].to_i unless new_allow_params[:field_validation][:maxLength].blank?
      new_allow_params[:field_validation][:maxDate] = Date.parse(new_allow_params[:field_validation][:maxDate]).strftime('%Y-%m-%d') unless new_allow_params[:field_validation][:maxDate].blank?
      new_allow_params[:field_validation][:minDate] = Date.parse(new_allow_params[:field_validation][:minDate]).strftime('%Y-%m-%d') unless new_allow_params[:field_validation][:minDate].blank?
    end

    return new_allow_params
  end

  def replace_component_type(type)
    case type
    when 'select_box'
      return 'select'
    else
      return type
    end
  end

  def prepare_json
    permit_jsons = []
    @form_elements.each do |el|
      new_hsh = {}
      el.attributes.each do |k, v|
        new_hsh[k.to_sym] = v if permit_keys.include? k.to_sym
        new_hsh[:validate] = v  if k == 'field_validation'



        new_hsh[:placeholder] = new_hsh[:field_placeholder]
        new_hsh[:type] = new_hsh[:component_type]

        # if(new_hsh[:type] == 'select_box')
        new_hsh[:type] = 'select' if new_hsh[:type] == 'select_box'
        # end
        if(new_hsh[:type] == 'select')
          new_hsh[:data] = v if k == 'datasets'
        end

        if(new_hsh[:type] == 'radio')
          new_hsh[:values] = v if k == 'datasets'
        end


        if(new_hsh[:type] == 'datetime')
          new_hsh[:format] = 'dd-MM-yyyy'
          new_hsh[:datePicker] = v  if k == 'field_validation'
        end
        new_hsh[:format] = '(999) 999-9999' if new_hsh[:type] == 'phoneNumber'
      end
      permit_jsons << new_hsh
    end

    permit_jsons << {type: 'button',action: 'submit',label: 'Submit',theme: 'primary'}

    return permit_jsons
  end

  def set_form
    @form = Form.find(params[:form_id])
  end

  def set_form_element
    @form_element = FormElement.find(params[:id])
  end

  def form_elements_params
    params.require(:form_element).permit(permit_keys)
  end

  def permit_keys
    [
      :type,
      :key, :label, :field_placeholder, :tooltip, :description, :component_type, :format,
      :field_validation => [:required, :maxLength, :minLength, :maxDate, :minDate],
      :date_validation => [:maxDate, :minDate],
      :datasets => [:values => [:label, :value]],
      :values => [:label, :value]
    ]
  end
end

app/controllers/forms_controller.rb
class FormsController < ApplicationController
  before_action :set_form, only: [:edit, :update, :destroy]

  def index
    @forms = Form.all
  end

  def new
    @form = Form.new
  end

  def create
    @form = Form.new(forms_params)
    if @form.save
      flash[:success] = "Form has been successfully created"
      redirect_to forms_path
    else
      render "new"
    end
  end

  def edit
  end

  def update
    if @form.update_attributes(forms_params)
      flash[:success] = "Form has been successfully updated"
      redirect_to forms_path
    end
  end

  def destroy
    if @form.destroy
      flash[:success] = "Form has been successfully deleted"
      redirect_to forms_path
    end
  end

  private
  def set_form
    @form = Form.find(params[:id])
  end

  def forms_params
    params.require(:form).permit(:title, :description, :is_active)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :verify_authenticity_token, except: [:create]
  before_action :unsafe_params, only: [:create]

  def params
    @_params || super
  end

  def index
  end

  def submit_form
  end

  def create
    puts "============================="
    # ap params[:data]
    # ap params[:metadata]
    data = unsafe_params[:data]
    data[:message] = 'Data has been saved successfully'
    # render json: data
    respond_to do |format|
      format.json { render json: data }
      format.html {}
    end
  end

  private
  def unsafe_params
    @_params = request.parameters
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/form_elements_helper.rb
module FormElementsHelper
end

app/helpers/forms_helper.rb
module FormsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/form_elements/_index.html.erb
<table class="table">
  <thead>
    <tr>
      <th>Field Type</th>
      <th>Key</th>
      <th>Label</th>

      <th>Placeholder</th>
      <th>Tooltip</th>
      <th>Description</th>

      <th>Format</th>
      <th>Validations</th>
      <th>Action</th>

    </tr>
  </thead>
  <tbody>
    <% @form_elements.each do |el, index|%>
      <tr>
        <td><%= el.component_type%></td>
        <td><%= el.key%></td>
        <td><%= el.label%></td>
        <td><%= el.field_placeholder%></td>
        <td><%= el.tooltip%></td>
        <td><%= el.description%></td>
        <td><%= el.format%></td>
        <td><%= el.field_validation%></td>

        <td>
          <%= link_to 'Edit', edit_form_form_element_path(@form, el), class: "btn btn-primary btn-xs" %>&nbsp;|&nbsp;
          <%= link_to 'Delete', form_form_element_path(@form, el), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-xs" %>
        </td>
      </tr>
    <%end%>
  </tbody>
</table>

app/views/form_elements/_new_form.html.erb
<%= form_for [@form, @form_element], :html => { :class => 'form-horizontal'}  do |f| %>
	<div class="form-group">
		<%= f.label "Title", :class => 'col-sm-2 control-label' %>
		<div class="col-sm-10">
			<%= f.select :component_type, FormElement.component_types, :class => 'form-control' %>
		</div>
	</div>

	<div class="form-group">
		<%= f.label "Key", :class => 'col-sm-2 control-label' %>
		<div class="col-sm-10">
			<%= f.text_field :key, :class => 'form-control' %>
		</div>
	</div>

  <div class="form-group">
		<%= f.label "Label", :class => 'col-sm-2 control-label' %>
		<div class="col-sm-10">
			<%= f.text_field :label, :class => 'form-control' %>
		</div>
	</div>

  <div class="form-group">
    <%= f.label "Placeholders", :class => 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_field :field_placeholder, :class => 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label "Tooltip", :class => 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_field :tooltip, :class => 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label "Description", :class => 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_field :description, :class => 'form-control' %>
    </div>
  </div>

	<div id="key_value_pair_select">
		<div class="form-group">
			<%= f.label "Datasets", :class => 'col-sm-2 control-label' %>
			<div class="col-sm-4">
				<input type="text" name="form_element[datasets][values][][label]" class="form-control" placeholder="Label" />
			</div>
			<div class="col-sm-4">
				<input type="text" name="form_element[datasets][values][][value]" class="form-control" placeholder="Value" />
			</div>
			<!-- <div class="col-sm-2">
				<a href="javascript:void(0)" onclick='return addNewKeyValue("sample-key-value-pair-select")' class='btn btn-success' ><span class="fa fa-plus fa-fw"></span> <%= t('button.add') %></a>
			</div> -->
		</div>

		<div class="form-group" id='sample-key-value-pair-select'>
			<%= f.label " ", :class => 'col-sm-2 control-label' %>
			<div class="col-sm-4">
				<input type="text" name="form_element[datasets][values][][label]" class="form-control" placeholder="Label" />
			</div>
			<div class="col-sm-4">
				<input type="text" name="form_element[datasets][values][][value]" class="form-control" placeholder="Value" />
			</div>
			<div class="col-sm-2">
				<a href="javascript:void(0)" onclick='return addNewKeyValue("sample-key-value-pair-select", "sample-key-value-pair-select")' class='btn btn-success' ><span class="fa fa-plus fa-fw"></span> <%= t('button.add') %></a>
			</div>
		</div>
	</div>

	<div id="key_value_pair_radio">
		<div class="form-group">
			<%= f.label "Datasets", :class => 'col-sm-2 control-label' %>
			<div class="col-sm-4">
				<input type="text" name="form_element[values][][label]" class="form-control" placeholder="Label" />
			</div>
			<div class="col-sm-4">
				<input type="text" name="form_element[values][][value]" class="form-control" placeholder="Value" />
			</div>
			<!-- <div class="col-sm-2">
				<a href="javascript:void(0)" onclick='return addNewKeyValue()' class='btn btn-success' ><span class="fa fa-plus fa-fw"></span> <%= t('button.add') %></a>
			</div> -->
		</div>

		<div class="form-group" id='sample-key-value-pair-radio'>
			<%= f.label " ", :class => 'col-sm-2 control-label' %>
			<div class="col-sm-4">
				<input type="text" name="form_element[values][][label]" class="form-control" placeholder="Label" />
			</div>
			<div class="col-sm-4">
				<input type="text" name="form_element[values][][value]" class="form-control" placeholder="Value" />
			</div>
			<div class="col-sm-2">
				<a href="javascript:void(0)" onclick='return addNewKeyValue("sample-key-value-pair-radio", "sample-key-value-pair-radio")' class='btn btn-success' ><span class="fa fa-plus fa-fw"></span> <%= t('button.add') %></a>
			</div>
		</div>
	</div>



	<div class="form-group">
    <%= f.label "Validation", :class => 'col-sm-2 control-label' %>
    <div class="col-sm-10">
			<% FormElement.validations.each do |k, v|%>
				<div class="checkbox" id="validation-<%=k%>">
					<label><input type="checkbox" name="form_element[field_validation][<%= k%>]" value="<%= v%>"><%= k%></label>
					<%if ['maxDate', 'minDate'].include?(k)%>
						<input type="text" class="datepicker" data-date-format="dd/mm/yyyy" name="form_element[field_validation][<%= k%>]" />
					<%elsif ['maxLength', 'minLength'].include?(k)%>
						<input type="number" name="form_element[field_validation][<%= k%>]" max='500' min='1' />
					<%end%>
				</div>
			<%end%>
    </div>
  </div>

	<div class="form-group">
		<div class="col-sm-offset-2 col-sm-4">
			<%= button_tag(:class => 'btn btn-success') do %>
				<span class="fa fa-save fa-fw"></span> <%= t('button.save') %>
			<% end %>
		</div>

		<div class="col-sm-offset-2 col-sm-4 pull-right">
			<%= link_to 'javascript:void(0)', id: 'cancel-add-new' ,class: 'btn btn-warning' do %>
				<span class="fa fa-remove fa-fw"></span> <%= t('button.cancel') %>
			<% end %>
		</div>

	</div>
<% end %>

<script type="text/javascript">
  $( document ).ready(function() {
		$('.datepicker').datepicker({
    	startDate: '-128y',
			endDate: '-18y'
		});
		// hide fields
		$("#key_value_pair_select").hide();
		$("#key_value_pair_radio").hide();
		$("#validation-maxDate").hide()
		$("#validation-minDate").hide();
		$("#validation-maxLength").show();
		$("#validation-minLength").show();

		// hide element based on component type
		$("#form_element_component_type").change(function(obj){
			console.log($(this).val())
			let selectedFieldType = $(this).val()
			if(selectedFieldType == 'select'){
				$("#key_value_pair_select").show();
				$("#key_value_pair_radio").hide();
				$("#validation-maxDate").hide()
				$("#validation-minDate").hide();
				$("#validation-maxLength").hide();
				$("#validation-minLength").hide();
			}else if (selectedFieldType == 'datetime') {
				$("#key_value_pair_select").hide();
				$("#key_value_pair_radio").hide();
				$("#validation-maxDate").show()
				$("#validation-minDate").show();
				$("#validation-maxLength").hide();
				$("#validation-minLength").hide();
			}else if (selectedFieldType == 'radio') {
				$("#key_value_pair_select").hide();
				$("#key_value_pair_radio").show();
				$("#validation-maxDate").hide();
				$("#validation-minDate").hide();
				$("#validation-maxLength").hide();
				$("#validation-minLength").hide();
			}else{
				// testfield, phone, email
				$("#key_value_pair_select").hide();
				$("#key_value_pair_radio").hide();
				$("#validation-maxDate").hide()
				$("#validation-minDate").hide();
				$("#validation-maxLength").show();
				$("#validation-minLength").show();
			}
		})


	})
</script>

app/views/form_elements/edit.html.erb
<h1>Add New Field</h1>
<%= render 'new_form' %>

app/views/form_elements/index.html.erb
<div class="page-title">
  <div class="title_left">
    <h1><i class="fa fa-list"></i> <%= @form.title%> Fields and their defination</h1>
  </div>
</div>

<ul class="nav nav-tabs" id="preview-tabs">
  <li class="preview active"><a href="javascript:void(0)">Preview</a></li>
  <li class="form"><a href="javascript:void(0)">Update fields</a></li>
</ul>

<div id="preview-section">
  <h3>Preview</h3>
  <%= render partial: '/shared/dynamic_form', locals: {preview_element: @preview_element}%>
</div>
<div id="form-section" style="display: none;">
  <h1>Elements</h1>
  <%= render partial: 'index', locals: {form_elements: @form_elements}%>
</div>

<hr size="30" />
<%= link_to 'Add New Field', "javascript:void(0)", id: 'add-new-field', class: "btn btn-success btn-xs" %>

<div id='new-field-form' style="display:none;">
  <h3>Add New Field</h3>
  <%= render 'new_form' %>
</div>

<script type="text/javascript">
  $( document ).ready(function() {
    // tabs toggle
    $("ul#preview-tabs>li").click(function(obj){
      console.log($(this))
      $("ul#preview-tabs>li").removeClass('active');
      $(this).addClass('active');
      $("#preview-section").toggle();
      $("#form-section").toggle();
    })

    // add new field
    $("#add-new-field").click(function(obj){
      $('#new-field-form').toggle();
      $(this).toggle();
    })

    $("#cancel-add-new").click(function(obj){
      $('#new-field-form').toggle();
      $('#add-new-field').toggle();
    })


  });

</script>

app/views/form_elements/preview.html.erb
<h1><%= @form.title%></h1>
<%= render partial: '/shared/dynamic_form', locals: {preview_element: @preview_element}%>

app/views/forms/_form_errors.html.erb
<% if @form.errors.any? %>
	<div class="panel panel-danger">
		<div class="panel-heading">
			<i class="fa fa-exclamation-triangle fa-fw"></i> <%= pluralize(@form.errors.count, "error") %> prohibited this user from being saved:
		</div>
		<div class="panel-body">
			<ul>
				<% @form.errors.full_messages.each do |message| %>
					<li><%= message %></li>
				<% end %>
			</ul>
		</div>
	</div>
<% end %>

app/views/forms/_new_form.html.erb
<%= form_for @form, :html => { :class => 'form-horizontal'}  do |f| %>
	<div class="form-group">
		<%= f.label "Title", :class => 'col-lg-2 control-label' %>
		<div class="col-lg-3">
			<%= f.text_field :title, :class => 'form-control' %>
		</div>
	</div>

	<div class="form-group">
		<%= f.label "Description", :class => 'col-lg-2 control-label' %>
		<div class="col-lg-3">
			<%= f.text_field :description, :class => 'form-control' %>
		</div>
	</div>

	<div class="form-group">
		<%= f.label "Form Description", :class => 'col-lg-2 control-label' %>
		<div class="col-lg-3">
			<%= f.check_box :is_active, :class => 'form-control' %>
		</div>
	</div>


	<div class="form-group">
		<div class="form-footer">
			<div class="form-footer-container">
				<div class="col-lg-12">
					<%= button_tag(:class => 'btn btn-success') do %>
						<span class="fa fa-save fa-fw"></span> <%= t('button.save') %>
					<% end %>
				</div>
			</div>
		</div>
	</div>
<% end %>

app/views/forms/edit.html.erb
<div class="row">
    <div class="col-lg-12">
        <h2 class="page-header">Forms</h2>
    </div>
</div>

<div class="row">
    <div class="col-lg-12">
		<%= render 'form_errors' %>
	</div>
</div>

<div class="row">
    <div class="col-lg-12">
		<%= render 'new_form' %>
	</div>
</div>

app/views/forms/index.html.erb
<h2>Available Forms</h2>
  <p>
    Above list has active and deactive both the forms
    <%= link_to '+ Add New', new_form_path, class: 'pull-right'%>
  </p>
  <table class="table">
    <thead>
      <tr>
        <th>Title</th>
        <th>Active</th>
        <th>Actions</th>
        <th>Field Definations</th>
        <th>Preview</th>
      </tr>
    </thead>
    <tbody>
      <% @forms.each do |form, index|%>
        <tr>
          <td title="<%= form.description%>"><%= form.title%></td>
          <td><%= form.is_active ? 'Yes' : 'No'%></td>
          <td>
            <%= link_to 'Edit', edit_form_path(form), class: "btn btn-primary btn-xs" %>&nbsp;|&nbsp;
            <%= link_to 'Delete', form_path(form), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-xs" %>
          </td>
          <td><%= link_to 'Fields', form_form_elements_path(form), class: "btn btn-success btn-xs" %></td>
          <td><%= link_to 'Preview', preview_form_path(form), class: "btn btn-success btn-xs" %></td>
        </tr>
      <%end%>
    </tbody>
  </table>

app/views/forms/new.html.erb
<div class="page-title">
  <div class="title_left">
    <h3><i class="fa fa-list"></i> Forms</h3>
  </div>
</div>

<div class="row">
    <div class="col-lg-12">
		<%= render 'form_errors' %>
	</div>
</div>

<div class="row">
    <div class="col-lg-12">
    	<div class="x_panel">
    		<div class="x_content">
    			<br/>
				<%= render 'new_form' %>
			</div>
		</div>
	</div>
</div>

app/views/home/index.html.erb
<h1>User Details Form</h1>
<p>Find me in app/views/home/index.html.erb</p>

<div id="formio"></formio>

<script src="http://formio.github.io/formio.js/dist/formio.full.js"></script>
<script type='text/javascript'>
Formio.icons = 'fontawesome';
Formio.createForm(document.getElementById('formio'), {
  components: [
    {
      type: 'textfield',
      key: 'firstName',
      label: 'First Name',
      placeholder: 'Enter your first name.',
      input: true,
      tooltip: 'Enter your <strong>First Name</strong>',
      description: 'Enter your <strong>First Name</strong>'
    },
    {
      type: 'textfield',
      key: 'lastName',
      label: 'Last Name',
      placeholder: 'Enter your last name',
      input: true,
      tooltip: 'Enter your <strong>Last Name</strong>',
      description: 'Enter your <strong>Last Name</strong>'
    },
    {
      type: 'email',
      key: 'email',
      label: 'Email',
      placeholder: 'Enter your Email',
      input: true,
      tooltip: 'Enter your <strong>Email ID</strong>',
      description: 'Enter your <strong>Email ID</strong>',
      validate: {
        required: true
      }
    },
    {
      type: 'datetime',
      key: 'dob',
      label: 'Date of Birth',
      placeholder: 'Enter your DOB',
      input: true,
      format: 'MM/dd/yyyy',
      enableDate: true,
      enableTime: false,
      datePicker: {
        maxDate: "1999-12-21",
        minDate: "1999-10-08"
      },
      defaultDate: "1999-12-31",
      validate: {
        required: true,
        invalid_date: 'invalid date',
      }
    },
    {
      type: 'phoneNumber',
      key: 'customerMobile',
      label: 'Mobile Number',
      placeholder: 'Enter your Mobile number',
      inputMask: "(999) 999-9999",
      input: true,
      validate: {
        required: true
      },
    },
    {
      type: "radio",
      label: "Gender",
      key: "gender",
      values: [
        {
          label: 'Male',
          value: 'm'
        },
        {
          label: 'Female',
          value: 'f'
        },
        {
          label: 'Other',
          value: 'o'
        }
      ]
    },
    {
      type: "select",
      label: "Favorite Things",
      key: "favoriteThings",
      placeholder: "These are a few of your favorite things...",
      data: {
        values: [
          {
            value: "raindropsOnRoses",
            label: "Raindrops on roses"
          },
          {
            value: "whiskersOnKittens",
            label: "Whiskers on Kittens"
          },
          {
            value: "brightCopperKettles",
            label: "Bright Copper Kettles"
          },
          {
            value: "warmWoolenMittens",
            label: "Warm Woolen Mittens"
          }
        ]
      },
      dataSrc: "values",
      template: "<span>{{ item.label }}</span>",
      multiple: false,
      input: false
    },
    {
      type: 'checkbox',
      label: 'As user I am agreed to terms and conditions',
      key: 'terms_and_condition',
      value: true,
      validate: {
        required: true
      },
    },
    {
      type: 'button',
      action: 'submit',
      label: 'Submit',
      theme: 'primary'
    }
  ]
}).then(function(form) {
  form.on('submit', function(submission) {
    console.log("Ajax call here")
    console.log(submission);
  });
});
</script>

app/views/home/submit_form.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

<div id="formio"></formio>

<script src="http://formio.github.io/formio.js/dist/formio.full.js"></script>
<script type='text/javascript'>
Formio.icons = 'fontawesome';
Formio.createForm(document.getElementById('formio'), 'https://examples.form.io/example')
  .then(function(form) {
    // Prevent the submission from going to the form.io server.
    form.nosubmit = true;

    // Triggered when they click the submit button.
    form.on('submit', function(submission) {
      console.log(submission);
      alert('Submission sent to custom endpoint. See developer console.');
      return fetch('https://hookb.in/ZrRRbJBe', {
          body: JSON.stringify(submission),
          headers: {
            'content-type': 'application/json'
          },
          method: 'POST',
          mode: 'cors',
        })
        .then(response => {
          form.emit('submitDone', submission)
          response.json()
        })
    });
  });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DynamicForms</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"> -->
    <link rel="stylesheet" href="http://formio.github.io/formio.js/dist/formio.full.min.css">
  </head>

  <body>
    <%= render partial: '/shared/header'%>
    <div class="container">

      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_dynamic_form.html.erb
<div id="formio"></div>
<%#= preview_element%>
<script src="http://formio.github.io/formio.js/dist/formio.full.js"></script>
<script type='text/javascript'>
Formio.icons = 'fontawesome';
Formio.createForm(document.getElementById('formio'), {
  components: <%= preview_element.to_s.html_safe%>
}).then(function(form) {
  form.on('submit', function(submission) {
    console.log("Ajax call here")
    console.log(submission);

    // alert('Submission sent to custom endpoint. See developer console.');
    return fetch('/home/create.json', {
      body: JSON.stringify(submission),
      headers: {
        'content-type': 'application/json'
      },
      method: 'POST',
      mode: 'cors',
    }).then(response => {
    form.emit('submitDone', submission)
    response.json()
  })


  });
});
</script>

app/views/shared/_header.html.erb
<div class="header">
  <a href="/" class="logo"><img class='logo' src='/assets/fa.png' alt='ForgeAhead Solutions'></a>
  <div class="header-right">
    <a class="active" href="/forms">Forms</a>
    <!-- <a href="#contact">Contact</a> -->
    <!-- <a href="#about">About</a> -->
  </div>
</div>